"use client";
import React, { useState, useRef, useEffect } from 'react';
import {
  Upload, Music, Image, Globe, Flag, AlertTriangle, User, FileText, Calendar, Star, Check, X, Play, Pause,
  ChevronLeft, ChevronRight, Loader2, Info, Link
} from 'lucide-react';

const MusicSubmissionForm = () => {
  const [currentStep, setCurrentStep] = useState(1);
  const [formData, setFormData] = useState({
    // Basic track info
    name: '', // Artist Name
    track_name: '',
    label: '',
    genre: '',
    language: '',
    country: '',
    is_explicit: false,
    description: '',

    // Files
    audio: null,
    image: null,
    lyrics_file: null,

    // Artist info
    first_name: '',
    middle_name: '',
    last_name: '',
    contact_phone: '',
    biography: '',

    // Additional info
    feature: '', // Featured Artists
    compose: '', // Composer
    record_label: '',
    spotify_url: '',
    itunes_url: '',
    video_url: '',
    lyrics: '', // Text lyrics
    is_cover: false,

    // Collaboration
    choice: 'solo', // solo, collaboration
    someone_full_name: '',
    someone_name: '', // This seems redundant with someone_full_name based on API but keeping for now
    someone_phone: '',
    someone_email: '',

    // API specific fields (will be populated dynamically or left empty if not relevant for submission directly)
    token: '', // Placeholder, ideally managed backend or from user session
    track_id: '', // Generated by backend
    duration: '00:00', // To be calculated from audio file
    music_upload_date: new Date().toISOString().split('T')[0],
  });

  const [uploadProgress, setUploadProgress] = useState({
    audio: 0,
    image: 0,
    lyrics_file: 0,
  });

  const [isSubmitting, setIsSubmitting] = useState(false);
  const [submissionStatus, setSubmissionStatus] = useState(null); // 'success', 'error', null
 const [audioPreview, setAudioPreview] = useState<string | null>(null); // CORRECTED LINE: Explicitly type it as string or null
  const [isPlaying, setIsPlaying] = useState(false);
  const audioRef = useRef<HTMLAudioElement | null>(null);
  const audioFileRef = useRef<File | null>(null);
   // CORRECTED: Explicitly type audioRef

  useEffect(() => {
    const audio = audioRef.current;
    if (audio) { // TypeScript now knows 'audio' is HTMLAudioElement here
      const handleEnded = () => setIsPlaying(false);
      audio.addEventListener('ended', handleEnded);
      return () => {
        audio.removeEventListener('ended', handleEnded);
        if (audioPreview) URL.revokeObjectURL(audioPreview); // Clean up object URL
      };
    }
  }, [audioPreview]);
  const steps = [
    { id: 1, title: 'Track Info', icon: Music },
    { id: 2, title: 'Media Upload', icon: Upload },
    { id: 3, title: 'Artist Details', icon: User },
    { id: 4, title: 'Additional Info', icon: FileText },
    { id: 5, title: 'Review & Submit', icon: Check }
  ];

  const genres = [
    'Afrobeats', 'Pop', 'Hip-Hop', 'R&B', 'Gospel', 'Highlife', 'Fuji', 'Juju',
    'Rock', 'Jazz', 'Reggae', 'Electronic', 'Classical', 'Folk', 'Country', 'Blues', 'Amapiano', 'Alternative'
  ];

  const languages = [
    'English', 'Yoruba', 'Igbo', 'Hausa', 'Pidgin', 'French', 'Spanish', 'Portuguese', 'Swahili', 'Arabic'
  ];

  const countries = [
    'Nigeria', 'Ghana', 'South Africa', 'Kenya', 'USA', 'UK', 'Canada', 'Australia', 'Germany', 'France', 'Brazil', 'India'
  ];

  // Effect to handle audio playback and cleanup
  useEffect(() => {
    const audio = audioRef.current;
    if (audio) {
      const handleEnded = () => setIsPlaying(false);
      audio.addEventListener('ended', handleEnded);
      return () => {
        audio.removeEventListener('ended', handleEnded);
        if (audioPreview) URL.revokeObjectURL(audioPreview); // Clean up object URL
      };
    }
  }, [audioPreview]);

  const handleInputChange = (field:string, value:any) => {
    setFormData(prev => ({ ...prev, [field]: value }));
  };



  const calculateAudioDuration = (file: File): Promise<string> => { // Corrected: Added type 'File' for 'file' and Promise<string> for return
    return new Promise((resolve) => {
      const audio = document.createElement('audio');
      audio.preload = 'metadata';
      audio.onloadedmetadata = () => {
        window.URL.revokeObjectURL(audio.src);
        const duration = Math.floor(audio.duration);
        const minutes = Math.floor(duration / 60);
        const seconds = duration % 60;
        resolve(`${minutes.toString().padStart(2, '0')}:${seconds.toString().padStart(2, '0')}`);
      };
      audio.onerror = () => { // Add error handling for audio loading
        console.error("Error loading audio metadata for duration calculation.");
        resolve("00:00"); // Resolve with default duration on error
      };
      audio.src = URL.createObjectURL(file);
    });
  };

  const handleFileUpload = async (field: 'audio' | 'image' | 'lyrics_file', file: File | null) => { // Corrected: Added types for field and file
    if (!file) return;

    setFormData(prev => ({ ...prev, [field]: file }));

    // Simulate upload progress
    setUploadProgress(prev => ({ ...prev, [field]: 0 })); // Reset progress
    let progress = 0;
    const interval = setInterval(() => {
      progress += 10;
      setUploadProgress(prev => ({ ...prev, [field]: progress }));
      if (progress >= 100) {
        clearInterval(interval);
        if (field === 'audio') {
          const url = URL.createObjectURL(file);
          setAudioPreview(url);
          audioFileRef.current = file; // Store file for duration calculation
          // Ensure audioFileRef.current is not null before passing
          if (audioFileRef.current) {
            calculateAudioDuration(audioFileRef.current).then(duration => {
              setFormData(prev => ({ ...prev, duration: duration }));
            });
          }
        }
      }
    }, 150);
  };


  const toggleAudioPreview = () => {
    if (!audioRef.current) return;

    if (isPlaying) {
      audioRef.current.pause();
    } else {
      audioRef.current.play();
    }
    setIsPlaying(!isPlaying);
  };

  const nextStep = () => {
    // Basic validation for current step before proceeding
    let isValid = true;
    if (currentStep === 1) {
      if (!formData.track_name || !formData.name || !formData.genre || !formData.language || !formData.country) {
        isValid = false;
        alert('Please fill in all required fields for Track Info.');
      }
    } else if (currentStep === 2) {
      if (!formData.audio || !formData.image) {
        isValid = false;
        alert('Please upload both Audio File and Cover Image.');
      } else if (uploadProgress.audio < 100 || uploadProgress.image < 100) {
        isValid = false;
        alert('Please wait for files to finish uploading.');
      }
    } else if (currentStep === 3) {
      if (!formData.first_name || !formData.last_name || !formData.contact_phone) {
        isValid = false;
        alert('Please fill in all required fields for Artist Details.');
      }
      if (formData.choice === 'collaboration' && (!formData.someone_full_name || !formData.someone_email)) {
        isValid = false;
        alert('Please fill in collaborator details for collaboration tracks.');
      }
    }

    if (isValid && currentStep < steps.length) {
      setCurrentStep(currentStep + 1);
      setSubmissionStatus(null); // Clear submission status on step change
    }
  };

  const prevStep = () => {
    if (currentStep > 1) {
      setCurrentStep(currentStep - 1);
      setSubmissionStatus(null); // Clear submission status on step change
    }
  };

  const submitForm = async () => {
    setIsSubmitting(true);
    setSubmissionStatus(null);

    const formDataToSubmit = new FormData();

    // Append all formData fields
    Object.keys(formData).forEach(key => {
      // Handle boolean to '1' or '0'
      if (key === 'is_explicit' || key === 'is_cover') {
        formDataToSubmit.append(key, formData[key] ? '1' : '0');
      }
      // Handle file uploads
      else if (formData[key] instanceof File) {
        formDataToSubmit.append(key, formData[key], formData[key].name);
      }
      // Handle other non-empty string/number values
      else if (formData[key] !== null && formData[key] !== undefined && formData[key] !== '') {
        formDataToSubmit.append(key, formData[key]);
      }
    });

    // Ensure token and music_upload_date are always sent if applicable
    // Note: 'token' and 'track_id' are likely managed server-side or from auth,
    // so sending empty string for now as per curl, but review this for production.
    formDataToSubmit.append('token', formData.token || '');
    formDataToSubmit.append('track_id', formData.track_id || '');
    formDataToSubmit.append('music_upload_date', formData.music_upload_date);


    try {
      const response = await fetch('https://singnify.com/api/v2/php/save-audio.php?API_KEY=7c6a180b36896a0a8c02787eeafb0e4c', {
        method: 'POST',
        body: formDataToSubmit
      });

      const result = await response.json();
      console.log('Submission result:', result);

      if (response.ok && result.status === 'success') { // Assuming your API returns { status: 'success' } on success
        setSubmissionStatus('success');
        // Optionally reset form here: setFormData(initialFormDataState);
      } else {
        setSubmissionStatus('error');
        console.error('API Error:', result.message || 'Unknown error');
      }
    } catch (error) {
      console.error('Network or Submission error:', error);
      setSubmissionStatus('error');
    } finally {
      setIsSubmitting(false);
    }
  };

  const getStepProgress = () => (currentStep / steps.length) * 100;

  const FileUploadComponent = ({ field, accept, label, icon: Icon, preview = null }) => (
    <div className="space-y-3">
      <label className="block text-sm font-medium text-white mb-2 flex items-center gap-2">
        <Icon className="w-4 h-4 text-purple-400" />
        {label}
        {field === 'audio' || field === 'image' ? <span className="text-red-400">*</span> : ''}
      </label>

      <div className="relative">
        <input
          type="file"
          accept={accept}
          onChange={(e) => handleFileUpload(field, e.target.files[0])}
          className="hidden"
          id={field}
        />
        <label
          htmlFor={field}
          className="block w-full p-6 border-2 border-dashed border-purple-500/50 rounded-xl hover:border-purple-400 transition-all cursor-pointer bg-slate-800/30 hover:bg-slate-800/50 group"
        >
          <div className="text-center">
            <Icon className="w-9 h-9 text-purple-400 mx-auto mb-3 group-hover:scale-110 transition-transform" />
            <p className="text-white font-semibold">
              {formData[field] ? formData[field].name : `Drag & Drop or Click to Upload ${label.toLowerCase()}`}
            </p>
            <p className="text-slate-400 text-xs mt-1">{accept}</p>
          </div>
        </label>

        {uploadProgress[field] > 0 && uploadProgress[field] < 100 && (
          <div className="mt-3">
            <div className="bg-slate-700 rounded-full h-2">
              <div
                className="bg-gradient-to-r from-purple-500 to-pink-500 h-2 rounded-full transition-all duration-300"
                style={{ width: `${uploadProgress[field]}%` }}
              />
            </div>
            <p className="text-xs text-slate-400 mt-1">{uploadProgress[field]}% uploaded</p>
          </div>
        )}

        {uploadProgress[field] === 100 && (
          <div className="mt-3 flex items-center gap-2 text-green-400">
            <Check className="w-4 h-4" />
            <span className="text-sm">Upload complete!</span>
          </div>
        )}
      </div>

      {preview && (
        <div className="mt-4 p-4 bg-slate-800/50 rounded-lg shadow-inner">
          {preview}
        </div>
      )}
    </div>
  );

  const renderStepContent = () => {
    switch (currentStep) {
      case 1:
        return (
          <div className="space-y-6 animate-fade-in-up">
            <h2 className="text-2xl font-bold text-white mb-6">Basic Track Information</h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div>
                <label className="block text-sm font-medium text-white mb-2">Track Name <span className="text-red-400">*</span></label>
                <input
                  type="text"
                  value={formData.track_name}
                  onChange={(e) => handleInputChange('track_name', e.target.value)}
                  className="w-full bg-slate-800/50 border border-slate-600 rounded-lg px-4 py-3 text-white placeholder-slate-500 focus:border-purple-500 focus:ring-2 focus:ring-purple-500/20 transition-all"
                  placeholder="Enter your track name"
                  required
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-white mb-2">Artist Name <span className="text-red-400">*</span></label>
                <input
                  type="text"
                  value={formData.name}
                  onChange={(e) => handleInputChange('name', e.target.value)}
                  className="w-full bg-slate-800/50 border border-slate-600 rounded-lg px-4 py-3 text-white placeholder-slate-500 focus:border-purple-500 focus:ring-2 focus:ring-purple-500/20 transition-all"
                  placeholder="Your artist name"
                  required
                />
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              <div>
                <label className="block text-sm font-medium text-white mb-2">Genre <span className="text-red-400">*</span></label>
                <select
                  value={formData.genre}
                  onChange={(e) => handleInputChange('genre', e.target.value)}
                  className="w-full bg-slate-800/50 border border-slate-600 rounded-lg px-4 py-3 text-white placeholder-slate-500 focus:border-purple-500 focus:ring-2 focus:ring-purple-500/20 appearance-none pr-8 cursor-pointer transition-all"
                  required
                >
                  <option value="">Select genre</option>
                  {genres.map(genre => (
                    <option key={genre} value={genre.toLowerCase()}>{genre}</option>
                  ))}
                </select>
              </div>

              <div>
                <label className="block text-sm font-medium text-white mb-2">Language <span className="text-red-400">*</span></label>
                <select
                  value={formData.language}
                  onChange={(e) => handleInputChange('language', e.target.value)}
                  className="w-full bg-slate-800/50 border border-slate-600 rounded-lg px-4 py-3 text-white placeholder-slate-500 focus:border-purple-500 focus:ring-2 focus:ring-purple-500/20 appearance-none pr-8 cursor-pointer transition-all"
                  required
                >
                  <option value="">Select language</option>
                  {languages.map(lang => (
                    <option key={lang} value={lang.toLowerCase()}>{lang}</option>
                  ))}
                </select>
              </div>

              <div>
                <label className="block text-sm font-medium text-white mb-2">Country <span className="text-red-400">*</span></label>
                <select
                  value={formData.country}
                  onChange={(e) => handleInputChange('country', e.target.value)}
                  className="w-full bg-slate-800/50 border border-slate-600 rounded-lg px-4 py-3 text-white placeholder-slate-500 focus:border-purple-500 focus:ring-2 focus:ring-purple-500/20 appearance-none pr-8 cursor-pointer transition-all"
                  required
                >
                  <option value="">Select country</option>
                  {countries.map(country => (
                    <option key={country} value={country.toLowerCase()}>{country}</option>
                  ))}
                </select>
              </div>
            </div>

            <div className="flex flex-wrap items-center gap-x-8 gap-y-4 pt-4">
              <label className="flex items-center space-x-2 cursor-pointer">
                <input
                  type="checkbox"
                  checked={formData.is_explicit}
                  onChange={(e) => handleInputChange('is_explicit', e.target.checked)}
                  className="w-5 h-5 text-purple-600 bg-slate-700 border-slate-500 rounded focus:ring-purple-500 transition-all"
                />
                <span className="text-white flex items-center gap-2 text-sm">
                  <AlertTriangle className="w-5 h-5 text-red-400" />
                  Explicit Content
                </span>
              </label>

              <label className="flex items-center space-x-2 cursor-pointer">
                <input
                  type="checkbox"
                  checked={formData.is_cover}
                  onChange={(e) => handleInputChange('is_cover', e.target.checked)}
                  className="w-5 h-5 text-purple-600 bg-slate-700 border-slate-500 rounded focus:ring-purple-500 transition-all"
                />
                <span className="text-white text-sm">Cover Song</span>
              </label>
            </div>

            <div>
              <label className="block text-sm font-medium text-white mb-2">Description</label>
              <textarea
                value={formData.description}
                onChange={(e) => handleInputChange('description', e.target.value)}
                rows={4}
                className="w-full bg-slate-800/50 border border-slate-600 rounded-lg px-4 py-3 text-white placeholder-slate-500 focus:border-purple-500 focus:ring-2 focus:ring-purple-500/20 transition-all"
                placeholder="Tell us about your track, its inspiration, or any interesting facts..."
              />
            </div>
          </div>
        );

      case 2:
        return (
          <div className="space-y-8 animate-fade-in-up">
            <h2 className="text-2xl font-bold text-white mb-6">Upload Your Media Files</h2>
            <FileUploadComponent
              field="audio"
              accept=".mp3,.wav,.flac"
              label="Audio File (MP3, WAV, FLAC)"
              icon={Music}
              preview={audioPreview && (
                <div className="flex items-center gap-4 bg-slate-900/50 p-3 rounded-lg border border-slate-700">
                  <button
                    onClick={toggleAudioPreview}
                    className="w-14 h-14 bg-purple-600 rounded-full flex items-center justify-center hover:bg-purple-700 transition-colors shadow-lg"
                  >
                    {isPlaying ? <Pause className="w-7 h-7 text-white" /> : <Play className="w-7 h-7 text-white" />}
                  </button>
                  <div className="flex-1">
                    <p className="text-white font-medium text-lg">{formData.audio?.name}</p>
                    <p className="text-slate-400 text-sm">Duration: {formData.duration}</p>
                  </div>
                  <audio ref={audioRef} src={audioPreview} onEnded={() => setIsPlaying(false)} />
                </div>
              )}
            />

            <FileUploadComponent
              field="image"
              accept="image/jpeg,image/png,image/gif"
              label="Cover Image (JPEG, PNG, GIF)"
              icon={Image}
              preview={formData.image && (
                <div className="flex items-center gap-4 bg-slate-900/50 p-3 rounded-lg border border-slate-700">
                  <img
                    src={URL.createObjectURL(formData.image)}
                    alt="Cover preview"
                    className="w-24 h-24 object-cover rounded-lg shadow-md border border-slate-600"
                  />
                  <div>
                    <p className="text-white font-medium text-lg">Cover Image</p>
                    <p className="text-slate-400 text-sm">{formData.image.name}</p>
                  </div>
                </div>
              )}
            />

            <FileUploadComponent
              field="lyrics_file"
              accept=".txt,.pdf,.doc,.docx"
              label="Lyrics File (Optional - TXT, PDF, DOCX)"
              icon={FileText}
            />

            <div>
              <label className="block text-sm font-medium text-white mb-2">Lyrics (Text - Optional)</label>
              <textarea
                value={formData.lyrics}
                onChange={(e) => handleInputChange('lyrics', e.target.value)}
                rows={8}
                className="w-full bg-slate-800/50 border border-slate-600 rounded-lg px-4 py-3 text-white placeholder-slate-500 focus:border-purple-500 focus:ring-2 focus:ring-purple-500/20 transition-all"
                placeholder="Enter your lyrics here..."
              />
            </div>
          </div>
        );

      case 3:
        return (
          <div className="space-y-6 animate-fade-in-up">
            <h2 className="text-2xl font-bold text-white mb-6">Artist Details</h2>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              <div>
                <label className="block text-sm font-medium text-white mb-2">First Name <span className="text-red-400">*</span></label>
                <input
                  type="text"
                  value={formData.first_name}
                  onChange={(e) => handleInputChange('first_name', e.target.value)}
                  className="w-full bg-slate-800/50 border border-slate-600 rounded-lg px-4 py-3 text-white placeholder-slate-500 focus:border-purple-500 focus:ring-2 focus:ring-purple-500/20 transition-all"
                  placeholder="Your first name"
                  required
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-white mb-2">Middle Name</label>
                <input
                  type="text"
                  value={formData.middle_name}
                  onChange={(e) => handleInputChange('middle_name', e.target.value)}
                  className="w-full bg-slate-800/50 border border-slate-600 rounded-lg px-4 py-3 text-white placeholder-slate-500 focus:border-purple-500 focus:ring-2 focus:ring-purple-500/20 transition-all"
                  placeholder="Your middle name (optional)"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-white mb-2">Last Name <span className="text-red-400">*</span></label>
                <input
                  type="text"
                  value={formData.last_name}
                  onChange={(e) => handleInputChange('last_name', e.target.value)}
                  className="w-full bg-slate-800/50 border border-slate-600 rounded-lg px-4 py-3 text-white placeholder-slate-500 focus:border-purple-500 focus:ring-2 focus:ring-purple-500/20 transition-all"
                  placeholder="Your last name"
                  required
                />
              </div>
            </div>

            <div>
              <label className="block text-sm font-medium text-white mb-2">Contact Phone <span className="text-red-400">*</span></label>
              <input
                type="tel"
                value={formData.contact_phone}
                onChange={(e) => handleInputChange('contact_phone', e.target.value)}
                className="w-full bg-slate-800/50 border border-slate-600 rounded-lg px-4 py-3 text-white placeholder-slate-500 focus:border-purple-500 focus:ring-2 focus:ring-purple-500/20 transition-all"
                placeholder="+234 801 234 5678"
                required
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-white mb-2">Biography</label>
              <textarea
                value={formData.biography}
                onChange={(e) => handleInputChange('biography', e.target.value)}
                rows={4}
                className="w-full bg-slate-800/50 border border-slate-600 rounded-lg px-4 py-3 text-white placeholder-slate-500 focus:border-purple-500 focus:ring-2 focus:ring-purple-500/20 transition-all"
                placeholder="Tell us about yourself as an artist, your journey, and achievements..."
              />
            </div>

            <div className="border-t border-slate-700 pt-6">
              <h3 className="text-xl font-semibold text-white mb-4 flex items-center gap-2">
                <Users className="w-5 h-5 text-purple-400" />Collaboration Details
              </h3>

              <div className="space-y-4">
                <div>
                  <label className="block text-sm font-medium text-white mb-2">Track Type</label>
                  <select
                    value={formData.choice}
                    onChange={(e) => handleInputChange('choice', e.target.value)}
                    className="w-full bg-slate-800/50 border border-slate-600 rounded-lg px-4 py-3 text-white focus:border-purple-500 focus:ring-2 focus:ring-purple-500/20 appearance-none pr-8 cursor-pointer transition-all"
                  >
                    <option value="solo">Solo Track</option>
                    <option value="collaboration">Collaboration Track</option>
                  </select>
                </div>

                {formData.choice === 'collaboration' && (
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4 animate-fade-in">
                    <div>
                      <label className="block text-sm font-medium text-white mb-2">Collaborator Full Name <span className="text-red-400">*</span></label>
                      <input
                        type="text"
                        value={formData.someone_full_name}
                        onChange={(e) => handleInputChange('someone_full_name', e.target.value)}
                        className="w-full bg-slate-800/50 border border-slate-600 rounded-lg px-4 py-3 text-white placeholder-slate-500 focus:border-purple-500 focus:ring-2 focus:ring-purple-500/20 transition-all"
                        placeholder="Collaborator's full name"
                        required
                      />
                    </div>

                    <div>
                      <label className="block text-sm font-medium text-white mb-2">Collaborator Email <span className="text-red-400">*</span></label>
                      <input
                        type="email"
                        value={formData.someone_email}
                        onChange={(e) => handleInputChange('someone_email', e.target.value)}
                        className="w-full bg-slate-800/50 border border-slate-600 rounded-lg px-4 py-3 text-white placeholder-slate-500 focus:border-purple-500 focus:ring-2 focus:ring-purple-500/20 transition-all"
                        placeholder="collaborator@example.com"
                        required
                      />
                    </div>
                    {/* Assuming someone_name and someone_phone are optional/redundant if full_name and email are collected */}
                    <div>
                      <label className="block text-sm font-medium text-white mb-2">Collaborator Phone (Optional)</label>
                      <input
                        type="tel"
                        value={formData.someone_phone}
                        onChange={(e) => handleInputChange('someone_phone', e.target.value)}
                        className="w-full bg-slate-800/50 border border-slate-600 rounded-lg px-4 py-3 text-white placeholder-slate-500 focus:border-purple-500 focus:ring-2 focus:ring-purple-500/20 transition-all"
                        placeholder="+234 xxx xxx xxxx"
                      />
                    </div>
                  </div>
                )}
              </div>
            </div>
          </div>
        );

      case 4:
        return (
          <div className="space-y-6 animate-fade-in-up">
            <h2 className="text-2xl font-bold text-white mb-6">Additional Track Information</h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div>
                <label className="block text-sm font-medium text-white mb-2">Featured Artists (Optional)</label>
                <input
                  type="text"
                  value={formData.feature}
                  onChange={(e) => handleInputChange('feature', e.target.value)}
                  className="w-full bg-slate-800/50 border border-slate-600 rounded-lg px-4 py-3 text-white placeholder-slate-500 focus:border-purple-500 focus:ring-2 focus:ring-purple-500/20 transition-all"
                  placeholder="e.g., feat. Wizkid, Burna Boy"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-white mb-2">Composer (Optional)</label>
                <input
                  type="text"
                  value={formData.compose}
                  onChange={(e) => handleInputChange('compose', e.target.value)}
                  className="w-full bg-slate-800/50 border border-slate-600 rounded-lg px-4 py-3 text-white placeholder-slate-500 focus:border-purple-500 focus:ring-2 focus:ring-purple-500/20 transition-all"
                  placeholder="Who composed this track?"
                />
              </div>
            </div>

            <div>
              <label className="block text-sm font-medium text-white mb-2">Record Label (Optional)</label>
              <input
                type="text"
                value={formData.record_label}
                onChange={(e) => handleInputChange('record_label', e.target.value)}
                className="w-full bg-slate-800/50 border border-slate-600 rounded-lg px-4 py-3 text-white placeholder-slate-500 focus:border-purple-500 focus:ring-2 focus:ring-purple-500/20 transition-all"
                placeholder="Your record label (if any)"
              />
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              <div>
                <label className="block text-sm font-medium text-white mb-2 flex items-center gap-2">
                  <Link className="w-4 h-4 text-blue-400" />
                  Spotify URL (Optional)
                </label>
                <input
                  type="url"
                  value={formData.spotify_url}
                  onChange={(e) => handleInputChange('spotify_url', e.target.value)}
                  className="w-full bg-slate-800/50 border border-slate-600 rounded-lg px-4 py-3 text-white placeholder-slate-500 focus:border-purple-500 focus:ring-2 focus:ring-purple-500/20 transition-all"
                  placeholder="https://open.spotify.com/track/..."
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-white mb-2 flex items-center gap-2">
                  <Link className="w-4 h-4 text-pink-400" />
                  iTunes URL (Optional)
                </label>
                <input
                  type="url"
                  value={formData.itunes_url}
                  onChange={(e) => handleInputChange('itunes_url', e.target.value)}
                  className="w-full bg-slate-800/50 border border-slate-600 rounded-lg px-4 py-3 text-white placeholder-slate-500 focus:border-purple-500 focus:ring-2 focus:ring-purple-500/20 transition-all"
                  placeholder="https://music.apple.com/us/album/..."
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-white mb-2 flex items-center gap-2">
                  <Link className="w-4 h-4 text-red-400" />
                  Video URL (YouTube/Vimeo - Optional)
                </label>
                <input
                  type="url"
                  value={formData.video_url}
                  onChange={(e) => handleInputChange('video_url', e.target.value)}
                  className="w-full bg-slate-800/50 border border-slate-600 rounded-lg px-4 py-3 text-white placeholder-slate-500 focus:border-purple-500 focus:ring-2 focus:ring-purple-500/20 transition-all"
                  placeholder="https://www.youtube.com/watch?v=..."
                />
              </div>
            </div>
          </div>
        );

      case 5:
        return (
          <div className="space-y-6 animate-fade-in-up">
            <h2 className="text-2xl font-bold text-white mb-6">Review Your Submission</h2>

            <div className="bg-slate-800/30 p-6 rounded-xl border border-slate-700/50 shadow-lg">
              <h3 className="text-xl font-semibold text-purple-400 mb-4 flex items-center gap-2">
                <Info className="w-5 h-5" /> Track & Artist Overview
              </h3>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-6 text-slate-200">
                <div>
                  <p className="mb-2"><span className="text-slate-400 font-medium">Track Name:</span> {formData.track_name || 'N/A'}</p>
                  <p className="mb-2"><span className="text-slate-400 font-medium">Artist Name:</span> {formData.name || 'N/A'}</p>
                  <p className="mb-2"><span className="text-slate-400 font-medium">Genre:</span> {formData.genre || 'N/A'}</p>
                  <p className="mb-2"><span className="text-slate-400 font-medium">Language:</span> {formData.language || 'N/A'}</p>
                  <p className="mb-2"><span className="text-slate-400 font-medium">Country:</span> {formData.country || 'N/A'}</p>
                  <p className="mb-2"><span className="text-slate-400 font-medium">Explicit Content:</span> {formData.is_explicit ? 'Yes' : 'No'}</p>
                  <p className="mb-2"><span className="text-slate-400 font-medium">Cover Song:</span> {formData.is_cover ? 'Yes' : 'No'}</p>
                </div>
                <div>
                  <p className="mb-2"><span className="text-slate-400 font-medium">Full Name:</span> {`${formData.first_name || ''} ${formData.middle_name || ''} ${formData.last_name || ''}`.trim() || 'N/A'}</p>
                  <p className="mb-2"><span className="text-slate-400 font-medium">Contact Phone:</span> {formData.contact_phone || 'N/A'}</p>
                  <p className="mb-2"><span className="text-slate-400 font-medium">Track Type:</span> {formData.choice === 'solo' ? 'Solo' : `Collaboration with ${formData.someone_full_name || 'N/A'}`}</p>
                  {formData.choice === 'collaboration' && formData.someone_email && (
                    <p className="mb-2"><span className="text-slate-400 font-medium">Collaborator Email:</span> {formData.someone_email}</p>
                  )}
                  <p className="mb-2"><span className="text-slate-400 font-medium">Record Label:</span> {formData.record_label || 'N/A'}</p>
                  <p className="mb-2"><span className="text-slate-400 font-medium">Upload Date:</span> {formData.music_upload_date}</p>
                </div>
              </div>

              <div className="mt-6 pt-4 border-t border-slate-700">
                <h4 className="font-medium text-purple-400 mb-2 flex items-center gap-2">
                  <Upload className="w-4 h-4" /> File Status
                </h4>
                <div className="space-y-1 text-sm text-slate-200">
                  <p className="flex items-center gap-2">
                    <Music className="w-4 h-4 text-purple-300" />
                    Audio File: {formData.audio ? <span className="text-green-400">✓ Uploaded ({formData.audio.name})</span> : <span className="text-red-400">✗ Missing</span>}
                  </p>
                  <p className="flex items-center gap-2">
                    <Image className="w-4 h-4 text-purple-300" />
                    Cover Image: {formData.image ? <span className="text-green-400">✓ Uploaded ({formData.image.name})</span> : <span className="text-red-400">✗ Missing</span>}
                  </p>
                  <p className="flex items-center gap-2">
                    <FileText className="w-4 h-4 text-purple-300" />
                    Lyrics (Text/File): {formData.lyrics_file || formData.lyrics ? <span className="text-green-400">✓ Provided</span> : <span className="text-slate-500">Optional (Not provided)</span>}
                  </p>
                </div>
              </div>
            </div>

            <div className="bg-gradient-to-r from-purple-900/20 to-pink-900/20 p-6 rounded-xl border border-purple-500/30 shadow-md">
              <h4 className="font-medium text-white mb-2 flex items-center gap-2">
                <AlertTriangle className="w-4 h-4 text-yellow-300" /> Important Notice
              </h4>
              <p className="text-slate-300 text-sm leading-relaxed">
                By clicking "Submit", you acknowledge that you own all necessary rights to this music and its components (audio, lyrics, artwork). You grant Singnify.com the non-exclusive right to distribute your music across its platforms and partners in accordance with our Terms of Service. Ensure all information is accurate to avoid delays.
              </p>
            </div>

            {submissionStatus === 'success' && (
              <div className="bg-green-600/20 text-green-300 p-4 rounded-lg flex items-center gap-3 animate-fade-in">
                <Check className="w-6 h-6" />
                <p className="font-semibold">Track submitted successfully! Thank you for your submission.</p>
              </div>
            )}
            {submissionStatus === 'error' && (
              <div className="bg-red-600/20 text-red-300 p-4 rounded-lg flex items-center gap-3 animate-fade-in">
                <X className="w-6 h-6" />
                <p className="font-semibold">Submission failed. Please check your inputs and try again. If the issue persists, contact support.</p>
              </div>
            )}
          </div>
        );

      default:
        return null;
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-purple-950 to-slate-900 p-4 sm:p-8 font-sans text-slate-100">
      <style jsx>{`
        @keyframes fadeIn {
          from { opacity: 0; transform: translateY(20px); }
          to { opacity: 1; transform: translateY(0); }
        }
        .animate-fade-in-up {
          animation: fadeIn 0.5s ease-out forwards;
        }
        .animate-fade-in {
          animation: fadeIn 0.5s ease-out forwards;
        }
        /* Custom styles for select arrow */
        select {
          background-image: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' fill='none' viewBox='0 0 20 20'%3e%3cpath stroke='%23a78bfa' stroke-linecap='round' stroke-linejoin='round' stroke-width='1.5' d='M6 8l4 4 4-4'/%3e%3c/svg%3e");
          background-repeat: no-repeat;
          background-position: right 0.7rem center;
          background-size: 1.5em 1.5em;
        }
      `}</style>
      <div className="max-w-6xl mx-auto py-8">
        {/* Header */}
        <div className="text-center mb-12">
          <h1 className="text-5xl font-extrabold bg-gradient-to-r from-purple-400 to-pink-400 bg-clip-text text-transparent mb-4 drop-shadow-lg">
            Submit Your Music to Singnify
          </h1>
          <p className="text-slate-300 text-xl">Empower your sound. Share your creativity with the world.</p>
        </div>

        {/* Progress Bar */}
        <div className="mb-12">
          <div className="flex justify-between items-center mb-4 relative z-10">
            {steps.map((step, index) => {
              const Icon = step.icon;
              const isActive = currentStep === step.id;
              const isCompleted = currentStep > step.id;

              return (
                <div key={step.id} className="flex items-center flex-1 md:flex-initial">
                  <div className={`relative w-14 h-14 rounded-full flex items-center justify-center border-2 transition-all duration-300 ease-in-out shadow-lg
                    ${isActive
                      ? 'bg-purple-600 border-purple-600 text-white transform scale-110'
                      : isCompleted
                        ? 'bg-green-500 border-green-500 text-white'
                        : 'bg-slate-700 border-slate-600 text-slate-400'
                    }`}>
                    {isCompleted ? <Check className="w-7 h-7" /> : <Icon className="w-7 h-7" />}
                    <span className={`absolute -bottom-7 text-xs font-semibold whitespace-nowrap transition-colors duration-300
                      ${isActive ? 'text-white' : 'text-slate-400'}`}>
                      {step.title}
                    </span>
                  </div>
                  {index < steps.length - 1 && (
                    <div className={`flex-1 h-1 mx-4 transition-colors duration-300
                      ${isCompleted ? 'bg-green-500' : 'bg-slate-700'}`} />
                  )}
                </div>
              );
            })}
          </div>

          <div className="w-full bg-slate-700 rounded-full h-2 mt-8">
            <div
              className="bg-gradient-to-r from-purple-500 to-pink-500 h-2 rounded-full transition-all duration-500 ease-out"
              style={{ width: `${getStepProgress()}%` }}
            />
          </div>
        </div>

        {/* Form Content */}
        <div className="bg-slate-800/40 backdrop-blur-md rounded-3xl p-6 sm:p-10 border border-slate-700/50 shadow-2xl">
          {renderStepContent()}
        </div>

        {/* Navigation */}
        <div className="flex justify-between mt-10">
          <button
            onClick={prevStep}
            disabled={currentStep === 1 || isSubmitting}
            className={`px-7 py-3 rounded-xl flex items-center gap-2 transition-all duration-300
              ${currentStep === 1 || isSubmitting
                ? 'bg-slate-700 text-slate-400 cursor-not-allowed opacity-60'
                : 'bg-slate-700 hover:bg-slate-600 text-white shadow-md'
              }`}
          >
            <ChevronLeft className="w-5 h-5" />
            Previous
          </button>

          {currentStep < steps.length ? (
            <button
              onClick={nextStep}
              className="px-7 py-3 bg-gradient-to-r from-purple-600 to-pink-600 text-white rounded-xl hover:from-purple-700 hover:to-pink-700 transition-all duration-300 shadow-lg flex items-center gap-2"
            >
              Next
              <ChevronRight className="w-5 h-5" />
            </button>
          ) : (
            <button
              onClick={submitForm}
              disabled={isSubmitting || submissionStatus === 'success'}
              className={`px-10 py-3 rounded-xl flex items-center gap-3 transition-all duration-300 text-lg font-semibold
                ${isSubmitting || submissionStatus === 'success'
                  ? 'bg-slate-700 text-slate-400 cursor-not-allowed opacity-60'
                  : 'bg-gradient-to-r from-green-500 to-teal-500 hover:from-green-600 hover:to-teal-600 text-white shadow-lg'
                }`}
            >
              {isSubmitting && <Loader2 className="w-6 h-6 animate-spin" />}
              {submissionStatus === 'success' ? 'Submitted!' : 'Submit Track'}
            </button>
          )}
        </div>
      </div>
    </div>
  );
};

export default MusicSubmissionForm;